/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author fernando
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private AtorJogador atorJogador;
    private JLabel[][] mapaPosicoes;
    private Icon piso;
    private Icon dado;
    private Icon[] seta1;
    private Icon[] seta2;
    private java.awt.Color corSelecao;
    private java.awt.Color corFundo;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(AtorJogador atorJogador) {
        
        //tira borda do Frame
        //this.setUndecorated(true);  
        
        this.atorJogador = atorJogador;
        this.corFundo = new java.awt.Color(255, 102, 51);
        this.corSelecao = new java.awt.Color(255, 188, 51);
        initComponents();
        this.carregaImagens();
        this.adicionaPosicoes();
        this.areaTabuleiro.setBackground(corFundo);
        this.mostrarTelaJogo(false);
        this.visivelDesistir(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTabuleiro = new javax.swing.JPanel();
        pos00 = new javax.swing.JLabel();
        pos10 = new javax.swing.JLabel();
        pos20 = new javax.swing.JLabel();
        pos30 = new javax.swing.JLabel();
        pos40 = new javax.swing.JLabel();
        pos50 = new javax.swing.JLabel();
        pos01 = new javax.swing.JLabel();
        pos11 = new javax.swing.JLabel();
        pos21 = new javax.swing.JLabel();
        pos31 = new javax.swing.JLabel();
        pos41 = new javax.swing.JLabel();
        pos51 = new javax.swing.JLabel();
        pos02 = new javax.swing.JLabel();
        pos12 = new javax.swing.JLabel();
        pos22 = new javax.swing.JLabel();
        pos32 = new javax.swing.JLabel();
        pos42 = new javax.swing.JLabel();
        pos52 = new javax.swing.JLabel();
        pos03 = new javax.swing.JLabel();
        pos13 = new javax.swing.JLabel();
        pos23 = new javax.swing.JLabel();
        pos33 = new javax.swing.JLabel();
        pos43 = new javax.swing.JLabel();
        pos53 = new javax.swing.JLabel();
        pos15 = new javax.swing.JLabel();
        pos05 = new javax.swing.JLabel();
        pos54 = new javax.swing.JLabel();
        pos44 = new javax.swing.JLabel();
        pos34 = new javax.swing.JLabel();
        pos04 = new javax.swing.JLabel();
        pos45 = new javax.swing.JLabel();
        pos14 = new javax.swing.JLabel();
        pos55 = new javax.swing.JLabel();
        pos24 = new javax.swing.JLabel();
        pos25 = new javax.swing.JLabel();
        pos35 = new javax.swing.JLabel();
        nomeJogador2 = new javax.swing.JLabel();
        nomeJogador1 = new javax.swing.JLabel();
        pontosMovimentoJog1_1 = new javax.swing.JLabel();
        pontosMovimentoJog1_2 = new javax.swing.JLabel();
        pontosMovimentoJog2_1 = new javax.swing.JLabel();
        pontosMovimentoJog2_2 = new javax.swing.JLabel();
        tituloPontosMovimentoJog1_1 = new javax.swing.JLabel();
        tituloPontosMovimentoJog2_1 = new javax.swing.JLabel();
        tituloPontosMovimentoJog2_2 = new javax.swing.JLabel();
        tituloPontosMovimentoJog1_2 = new javax.swing.JLabel();
        inicio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuJogo = new javax.swing.JMenu();
        itemMenuIniciar = new javax.swing.JMenuItem();
        itemMenuDesistir = new javax.swing.JMenuItem();
        itemMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        areaTabuleiro.setBackground(new java.awt.Color(255, 102, 51));
        areaTabuleiro.setMinimumSize(new java.awt.Dimension(640, 480));
        areaTabuleiro.setPreferredSize(new java.awt.Dimension(640, 480));

        pos00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos00.setMaximumSize(new java.awt.Dimension(10, 10));
        pos00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos00MouseClicked(evt);
            }
        });

        pos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos10.setMaximumSize(new java.awt.Dimension(10, 10));
        pos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos10MouseClicked(evt);
            }
        });

        pos20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos20.setMaximumSize(new java.awt.Dimension(10, 10));
        pos20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos20MouseClicked(evt);
            }
        });

        pos30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos30.setMaximumSize(new java.awt.Dimension(10, 10));
        pos30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos30MouseClicked(evt);
            }
        });

        pos40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos40.setMaximumSize(new java.awt.Dimension(10, 10));
        pos40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos40MouseClicked(evt);
            }
        });

        pos50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos50.setMaximumSize(new java.awt.Dimension(10, 10));
        pos50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos50MouseClicked(evt);
            }
        });

        pos01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos01.setMaximumSize(new java.awt.Dimension(10, 10));
        pos01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos01MouseClicked(evt);
            }
        });

        pos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos11.setMaximumSize(new java.awt.Dimension(10, 10));
        pos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos11MouseClicked(evt);
            }
        });

        pos21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos21.setMaximumSize(new java.awt.Dimension(10, 10));
        pos21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos21MouseClicked(evt);
            }
        });

        pos31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos31.setMaximumSize(new java.awt.Dimension(10, 10));
        pos31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos31MouseClicked(evt);
            }
        });

        pos41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos41.setMaximumSize(new java.awt.Dimension(10, 10));
        pos41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos41MouseClicked(evt);
            }
        });

        pos51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos51.setMaximumSize(new java.awt.Dimension(10, 10));
        pos51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos51MouseClicked(evt);
            }
        });

        pos02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos02.setMaximumSize(new java.awt.Dimension(10, 10));
        pos02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos02MouseClicked(evt);
            }
        });

        pos12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos12.setMaximumSize(new java.awt.Dimension(10, 10));
        pos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos12MouseClicked(evt);
            }
        });

        pos22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos22.setMaximumSize(new java.awt.Dimension(10, 10));
        pos22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos22MouseClicked(evt);
            }
        });

        pos32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos32.setMaximumSize(new java.awt.Dimension(10, 10));
        pos32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos32MouseClicked(evt);
            }
        });

        pos42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos42.setMaximumSize(new java.awt.Dimension(10, 10));
        pos42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos42MouseClicked(evt);
            }
        });

        pos52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos52.setMaximumSize(new java.awt.Dimension(10, 10));
        pos52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos52MouseClicked(evt);
            }
        });

        pos03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos03.setMaximumSize(new java.awt.Dimension(10, 10));
        pos03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos03MouseClicked(evt);
            }
        });

        pos13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos13.setMaximumSize(new java.awt.Dimension(10, 10));
        pos13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos13MouseClicked(evt);
            }
        });

        pos23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos23.setMaximumSize(new java.awt.Dimension(10, 10));
        pos23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos23MouseClicked(evt);
            }
        });

        pos33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos33.setMaximumSize(new java.awt.Dimension(10, 10));
        pos33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos33MouseClicked(evt);
            }
        });

        pos43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos43.setMaximumSize(new java.awt.Dimension(10, 10));
        pos43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos43MouseClicked(evt);
            }
        });

        pos53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos53.setMaximumSize(new java.awt.Dimension(10, 10));
        pos53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos53MouseClicked(evt);
            }
        });

        pos15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos15.setMaximumSize(new java.awt.Dimension(10, 10));
        pos15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos15MouseClicked(evt);
            }
        });

        pos05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos05.setMaximumSize(new java.awt.Dimension(10, 10));
        pos05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos05MouseClicked(evt);
            }
        });

        pos54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos54.setMaximumSize(new java.awt.Dimension(10, 10));
        pos54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos54MouseClicked(evt);
            }
        });

        pos44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos44.setMaximumSize(new java.awt.Dimension(10, 10));
        pos44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos44MouseClicked(evt);
            }
        });

        pos34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos34.setMaximumSize(new java.awt.Dimension(10, 10));
        pos34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos34MouseClicked(evt);
            }
        });

        pos04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos04.setMaximumSize(new java.awt.Dimension(10, 10));
        pos04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos04MouseClicked(evt);
            }
        });

        pos45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos45.setMaximumSize(new java.awt.Dimension(10, 10));
        pos45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos45MouseClicked(evt);
            }
        });

        pos14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos14.setMaximumSize(new java.awt.Dimension(10, 10));
        pos14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos14MouseClicked(evt);
            }
        });

        pos55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos55.setMaximumSize(new java.awt.Dimension(10, 10));
        pos55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos55MouseClicked(evt);
            }
        });

        pos24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos24.setMaximumSize(new java.awt.Dimension(10, 10));
        pos24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos24MouseClicked(evt);
            }
        });

        pos25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos25.setMaximumSize(new java.awt.Dimension(10, 10));
        pos25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos25MouseClicked(evt);
            }
        });

        pos35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"))); // NOI18N
        pos35.setMaximumSize(new java.awt.Dimension(10, 10));
        pos35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos35MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout areaTabuleiroLayout = new javax.swing.GroupLayout(areaTabuleiro);
        areaTabuleiro.setLayout(areaTabuleiroLayout);
        areaTabuleiroLayout.setHorizontalGroup(
            areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTabuleiroLayout.createSequentialGroup()
                .addGroup(areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pos05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        areaTabuleiroLayout.setVerticalGroup(
            areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaTabuleiroLayout.createSequentialGroup()
                .addGroup(areaTabuleiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaTabuleiroLayout.createSequentialGroup()
                        .addComponent(pos00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areaTabuleiroLayout.createSequentialGroup()
                        .addComponent(pos01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areaTabuleiroLayout.createSequentialGroup()
                        .addComponent(pos02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areaTabuleiroLayout.createSequentialGroup()
                        .addComponent(pos03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areaTabuleiroLayout.createSequentialGroup()
                        .addComponent(pos04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(areaTabuleiroLayout.createSequentialGroup()
                        .addComponent(pos05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        nomeJogador2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeJogador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeJogador2.setText("Nome Jogador1");

        nomeJogador1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nomeJogador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeJogador1.setText("Nome Jogador2");

        pontosMovimentoJog1_1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pontosMovimentoJog1_1.setText("6");

        pontosMovimentoJog1_2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pontosMovimentoJog1_2.setText("6");

        pontosMovimentoJog2_1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pontosMovimentoJog2_1.setText("6");

        pontosMovimentoJog2_2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        pontosMovimentoJog2_2.setText("6");

        tituloPontosMovimentoJog1_1.setText("Movimento Peca 1");
        tituloPontosMovimentoJog1_1.setName("tituloPontosMovimentoJog1_1"); // NOI18N

        tituloPontosMovimentoJog2_1.setText("Movimento Peca 1");
        tituloPontosMovimentoJog2_1.setName("tituloPontosMovimentoJog2_1"); // NOI18N

        tituloPontosMovimentoJog2_2.setText("Movimento Peca 2");
        tituloPontosMovimentoJog2_2.setName("tituloPontosMovimentoJog2_2"); // NOI18N

        tituloPontosMovimentoJog1_2.setText("Movimento Peca 2");
        tituloPontosMovimentoJog1_2.setName("tituloPontosMovimentoJog1_2"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Vijaya", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SHUTDOWN");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/punhalada.jpg"))); // NOI18N

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        menuJogo.setText("Jogo");

        itemMenuIniciar.setText("Iniciar");
        itemMenuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuIniciarActionPerformed(evt);
            }
        });
        menuJogo.add(itemMenuIniciar);

        itemMenuDesistir.setText("Desistir");
        itemMenuDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuDesistirActionPerformed(evt);
            }
        });
        menuJogo.add(itemMenuDesistir);

        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuJogo.add(itemMenuSair);

        jMenuBar1.add(menuJogo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloPontosMovimentoJog1_1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(pontosMovimentoJog2_1)
                                            .addComponent(pontosMovimentoJog1_1)))
                                    .addComponent(tituloPontosMovimentoJog2_1))
                                .addGap(91, 91, 91)
                                .addComponent(nomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloPontosMovimentoJog2_2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(areaTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pontosMovimentoJog2_2)
                                    .addComponent(pontosMovimentoJog1_2)
                                    .addComponent(tituloPontosMovimentoJog1_2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(nomeJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nomeJogador1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaTabuleiro, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloPontosMovimentoJog1_1)
                            .addComponent(tituloPontosMovimentoJog1_2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pontosMovimentoJog1_2)
                            .addComponent(pontosMovimentoJog1_1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pontosMovimentoJog2_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloPontosMovimentoJog2_1))
                    .addComponent(nomeJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pontosMovimentoJog2_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloPontosMovimentoJog2_2)))
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pontosMovimentoJog2_2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void pos00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos00MouseClicked
    this.atorJogador.click(0, 0);
}//GEN-LAST:event_pos00MouseClicked

private void pos01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos01MouseClicked
    this.atorJogador.click(0, 1);
}//GEN-LAST:event_pos01MouseClicked

private void pos02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos02MouseClicked
    this.atorJogador.click(0, 2);
}//GEN-LAST:event_pos02MouseClicked

private void pos03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos03MouseClicked
    this.atorJogador.click(0, 3);
}//GEN-LAST:event_pos03MouseClicked

private void pos04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos04MouseClicked
    this.atorJogador.click(0, 4);
}//GEN-LAST:event_pos04MouseClicked

private void pos05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos05MouseClicked
    this.atorJogador.click(0, 5);
}//GEN-LAST:event_pos05MouseClicked

private void pos10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos10MouseClicked
    this.atorJogador.click(1, 0);
}//GEN-LAST:event_pos10MouseClicked

private void pos11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos11MouseClicked
    this.atorJogador.click(1, 1);
}//GEN-LAST:event_pos11MouseClicked

private void pos12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos12MouseClicked
    this.atorJogador.click(1, 2);
}//GEN-LAST:event_pos12MouseClicked

private void pos13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos13MouseClicked
    this.atorJogador.click(1, 3);
}//GEN-LAST:event_pos13MouseClicked

private void pos14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos14MouseClicked
    this.atorJogador.click(1, 4);
}//GEN-LAST:event_pos14MouseClicked

private void pos15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos15MouseClicked
    this.atorJogador.click(1, 5);
}//GEN-LAST:event_pos15MouseClicked

private void pos20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos20MouseClicked
    this.atorJogador.click(2, 0);
}//GEN-LAST:event_pos20MouseClicked

private void pos21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos21MouseClicked
    this.atorJogador.click(2, 1);
}//GEN-LAST:event_pos21MouseClicked

private void pos22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos22MouseClicked
    this.atorJogador.click(2, 2);
}//GEN-LAST:event_pos22MouseClicked

private void pos23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos23MouseClicked
    this.atorJogador.click(2, 3);
}//GEN-LAST:event_pos23MouseClicked

private void pos24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos24MouseClicked
    this.atorJogador.click(2, 4);
}//GEN-LAST:event_pos24MouseClicked

private void pos25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos25MouseClicked
    this.atorJogador.click(2, 5);
}//GEN-LAST:event_pos25MouseClicked

private void pos30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos30MouseClicked
    this.atorJogador.click(3, 0);
}//GEN-LAST:event_pos30MouseClicked

private void pos31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos31MouseClicked
    this.atorJogador.click(3, 1);
}//GEN-LAST:event_pos31MouseClicked

private void pos32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos32MouseClicked
    this.atorJogador.click(3, 2);
}//GEN-LAST:event_pos32MouseClicked

private void pos33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos33MouseClicked
    this.atorJogador.click(3, 3);
}//GEN-LAST:event_pos33MouseClicked

private void pos34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos34MouseClicked
    this.atorJogador.click(3, 4);
}//GEN-LAST:event_pos34MouseClicked

private void pos35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos35MouseClicked
    this.atorJogador.click(3, 5);
}//GEN-LAST:event_pos35MouseClicked

private void pos40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos40MouseClicked
    this.atorJogador.click(4, 0);
}//GEN-LAST:event_pos40MouseClicked

private void pos41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos41MouseClicked
    this.atorJogador.click(4, 1);
}//GEN-LAST:event_pos41MouseClicked

private void pos42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos42MouseClicked
    this.atorJogador.click(4, 2);
}//GEN-LAST:event_pos42MouseClicked

private void pos43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos43MouseClicked
    this.atorJogador.click(4, 3);
}//GEN-LAST:event_pos43MouseClicked

private void pos44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos44MouseClicked
    this.atorJogador.click(4, 4);
}//GEN-LAST:event_pos44MouseClicked

private void pos45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos45MouseClicked
    this.atorJogador.click(4, 5);
}//GEN-LAST:event_pos45MouseClicked

private void pos50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos50MouseClicked
    this.atorJogador.click(5, 0);
}//GEN-LAST:event_pos50MouseClicked

private void pos51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos51MouseClicked
    this.atorJogador.click(5, 1);
}//GEN-LAST:event_pos51MouseClicked

private void pos52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos52MouseClicked
    this.atorJogador.click(5, 2);
}//GEN-LAST:event_pos52MouseClicked

private void pos53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos53MouseClicked
    this.atorJogador.click(5, 3);
}//GEN-LAST:event_pos53MouseClicked

private void pos54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos54MouseClicked
    this.atorJogador.click(5, 4);
}//GEN-LAST:event_pos54MouseClicked

private void pos55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos55MouseClicked
    this.atorJogador.click(5, 5);
}//GEN-LAST:event_pos55MouseClicked

private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
    System.exit(0);
}//GEN-LAST:event_itemMenuSairActionPerformed

private void itemMenuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuIniciarActionPerformed
    this.atorJogador.iniciar();
}//GEN-LAST:event_itemMenuIniciarActionPerformed

    private void itemMenuDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuDesistirActionPerformed
        this.atorJogador.desistir(false);
    }//GEN-LAST:event_itemMenuDesistirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaTabuleiro;
    private javax.swing.JPanel inicio;
    private javax.swing.JMenuItem itemMenuDesistir;
    private javax.swing.JMenuItem itemMenuIniciar;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuJogo;
    private javax.swing.JLabel nomeJogador1;
    private javax.swing.JLabel nomeJogador2;
    private javax.swing.JLabel pontosMovimentoJog1_1;
    private javax.swing.JLabel pontosMovimentoJog1_2;
    private javax.swing.JLabel pontosMovimentoJog2_1;
    private javax.swing.JLabel pontosMovimentoJog2_2;
    private javax.swing.JLabel pos00;
    private javax.swing.JLabel pos01;
    private javax.swing.JLabel pos02;
    private javax.swing.JLabel pos03;
    private javax.swing.JLabel pos04;
    private javax.swing.JLabel pos05;
    private javax.swing.JLabel pos10;
    private javax.swing.JLabel pos11;
    private javax.swing.JLabel pos12;
    private javax.swing.JLabel pos13;
    private javax.swing.JLabel pos14;
    private javax.swing.JLabel pos15;
    private javax.swing.JLabel pos20;
    private javax.swing.JLabel pos21;
    private javax.swing.JLabel pos22;
    private javax.swing.JLabel pos23;
    private javax.swing.JLabel pos24;
    private javax.swing.JLabel pos25;
    private javax.swing.JLabel pos30;
    private javax.swing.JLabel pos31;
    private javax.swing.JLabel pos32;
    private javax.swing.JLabel pos33;
    private javax.swing.JLabel pos34;
    private javax.swing.JLabel pos35;
    private javax.swing.JLabel pos40;
    private javax.swing.JLabel pos41;
    private javax.swing.JLabel pos42;
    private javax.swing.JLabel pos43;
    private javax.swing.JLabel pos44;
    private javax.swing.JLabel pos45;
    private javax.swing.JLabel pos50;
    private javax.swing.JLabel pos51;
    private javax.swing.JLabel pos52;
    private javax.swing.JLabel pos53;
    private javax.swing.JLabel pos54;
    private javax.swing.JLabel pos55;
    private javax.swing.JLabel tituloPontosMovimentoJog1_1;
    private javax.swing.JLabel tituloPontosMovimentoJog1_2;
    private javax.swing.JLabel tituloPontosMovimentoJog2_1;
    private javax.swing.JLabel tituloPontosMovimentoJog2_2;
    // End of variables declaration//GEN-END:variables

    private void adicionaPosicoes() {
        mapaPosicoes = new JLabel[6][6];
        mapaPosicoes[0][0] = pos00;
        mapaPosicoes[0][1] = pos01;
        mapaPosicoes[0][2] = pos02;
        mapaPosicoes[0][3] = pos03;
        mapaPosicoes[0][4] = pos04;
        mapaPosicoes[0][5] = pos05;
        mapaPosicoes[1][0] = pos10;
        mapaPosicoes[1][1] = pos11;
        mapaPosicoes[1][2] = pos12;
        mapaPosicoes[1][3] = pos13;
        mapaPosicoes[1][4] = pos14;
        mapaPosicoes[1][5] = pos15;
        mapaPosicoes[2][0] = pos20;
        mapaPosicoes[2][1] = pos21;
        mapaPosicoes[2][2] = pos22;
        mapaPosicoes[2][3] = pos23;
        mapaPosicoes[2][4] = pos24;
        mapaPosicoes[2][5] = pos25;
        mapaPosicoes[3][0] = pos30;
        mapaPosicoes[3][1] = pos31;
        mapaPosicoes[3][2] = pos32;
        mapaPosicoes[3][3] = pos33;
        mapaPosicoes[3][4] = pos34;
        mapaPosicoes[3][5] = pos35;
        mapaPosicoes[4][0] = pos40;
        mapaPosicoes[4][1] = pos41;
        mapaPosicoes[4][2] = pos42;
        mapaPosicoes[4][3] = pos43;
        mapaPosicoes[4][4] = pos44;
        mapaPosicoes[4][5] = pos45;
        mapaPosicoes[5][0] = pos50;
        mapaPosicoes[5][1] = pos51;
        mapaPosicoes[5][2] = pos52;
        mapaPosicoes[5][3] = pos53;
        mapaPosicoes[5][4] = pos54;
        mapaPosicoes[5][5] = pos55;

    }

    private void carregaImagens() {
        piso = new javax.swing.ImageIcon(getClass().getResource("/Resources/piso1.png"));
        dado = new javax.swing.ImageIcon(getClass().getResource("/Resources/dados.gif"));
        seta1 = new Icon[4];
        seta2 = new Icon[4];
        seta1[0] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo1_cima.gif"));
        seta1[1] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo1_dir.gif"));
        seta1[2] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo1_baixo.gif"));
        seta1[3] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo1_esq.gif"));
        seta2[0] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo2_cima.gif"));
        seta2[1] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo2_dir.gif"));
        seta2[2] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo2_baixo.gif"));
        seta2[3] = new javax.swing.ImageIcon(getClass().getResource("/Resources/robo2_esq.gif"));
    }

    public String solicitaDados(String mensagem) {
        return JOptionPane.showInputDialog(this, mensagem);
    }

    public void mostrarTelaJogo(boolean exibir) {
        this.inicio.setVisible(!exibir);
        this.areaTabuleiro.setVisible(exibir);
        this.mostrarPontosMovimento(exibir);
        this.habilitarIniciar(!exibir);
        this.visivelIniciar(!exibir);
        this.visivelDesistir(exibir);
    }

    public void mostrarPontosMovimento(boolean exibir) {
        nomeJogador2.setVisible(exibir);
        nomeJogador1.setVisible(exibir);
        pontosMovimentoJog1_1.setVisible(exibir);
        pontosMovimentoJog1_2.setVisible(exibir);
        pontosMovimentoJog2_1.setVisible(exibir);
        pontosMovimentoJog2_2.setVisible(exibir);
        tituloPontosMovimentoJog1_1.setVisible(exibir);
        tituloPontosMovimentoJog1_2.setVisible(exibir);
        tituloPontosMovimentoJog2_1.setVisible(exibir);
        tituloPontosMovimentoJog2_2.setVisible(exibir);
        if (!exibir){
            this.pontosMovimentoJog1_1.setText("0");
            this.pontosMovimentoJog1_2.setText("0");
            this.pontosMovimentoJog2_1.setText("0");
            this.pontosMovimentoJog2_2.setText("0");
        }
    }

    public void habilitarIniciar(boolean habilitar) {
        this.itemMenuIniciar.setEnabled(habilitar);
    }

    public void visivelIniciar(boolean visivel) {
        this.itemMenuIniciar.setVisible(visivel);
    }

    public void habilitarDesistir(boolean habilitar) {
        this.itemMenuDesistir.setEnabled(habilitar);
    }

    public void visivelDesistir(boolean visivel) {
        this.itemMenuDesistir.setVisible(visivel);
    }

    public void setNomeJogador1(String nome) {
        this.nomeJogador1.setText(nome);
    }

    public void setNomeJogador2(String nome) {
        this.nomeJogador2.setText(nome);
    }
    
    public void mostrarAnimacaoDado(int[] num) {
        JOptionPane.showMessageDialog(this, "Sua Vez de Jogar.\nO restultado rolado nos dados foi: \nPeça1: " + num[0] + "   Peça2: " + num[1], "Rolou os dados.", JOptionPane.INFORMATION_MESSAGE, dado);
    }

    public void informaPartidaEmAndamento() {
        JOptionPane.showMessageDialog(this, "Já há uma partida em andamento. Encerre a partida primeiro se quiser iniciar outra.", "Erro ao Iniciar.", JOptionPane.ERROR_MESSAGE);
    }

    public void informaFaltaDeJogadores() {

    }

    public void informaErro(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }

    public JLabel[][] getMapaPosicoes() {
        return mapaPosicoes;
    }

    public Icon[] getSeta1() {
        return seta1;
    }

    public Icon[] getSeta2() {
        return seta2;
    }

    public Icon getPiso() {
        return piso;
    }

    public JLabel getPontosMovimentoJog1_1() {
        return pontosMovimentoJog1_1;
    }

    public JLabel getPontosMovimentoJog1_2() {
        return pontosMovimentoJog1_2;
    }

    public JLabel getPontosMovimentoJog2_1() {
        return pontosMovimentoJog2_1;
    }

    public JLabel getPontosMovimentoJog2_2() {
        return pontosMovimentoJog2_2;
    }

    public JLabel getNomeJogador1() {
        return nomeJogador2;
    }

    public JLabel getNomeJogador2() {
        return nomeJogador1;
    }

    public void mudaCorSelecao(boolean selecionado) {
        if (selecionado) {
            areaTabuleiro.setBackground(corSelecao);
        } else {
            areaTabuleiro.setBackground(corFundo);
        }
        this.repaint();
    }
}
